exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- submission.md
- include_md.html

# 2. Installed Gems
plugins:
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Rome # Timezone for blog posts and alike

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Assessment on the Status of CyberSecurity in Denmark" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/images/ascd_logo.png" # Site logo, also used in jekyll-seo-tag
description: "Assessment on the Status of CyberSecurity in Denmark" # Site description and default description, also used in jekyll-seo-tag
baseurl: "" # Site url, also used in jekyll-seo-tag
google_analytics_code: "UA-XXXXXXXX"
google_verification_code: "XXXXXXX"
avatarurl: "/assets/images/favicon.ico" # Uses avatars for favicons to get multiple sites, eg Gravatar, Twitter, GitHub
header_left: |
  <h3><a href="/"><img class="img-responsive" style="max-height:2em;" src="/assets/images/ascd_logo.png" alt=""></a></h3>
header_right: ""
# 8. Site navigation
navigation_header:
  Home: /
  Survey: /survey/
  About: /about/
  Contact: /contact/